// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeRub1zvJQnFl7HaiYCBj5WdybSlDs3DA',
    appId: '1:886615549436:web:5803d50ec7a829d4693e79',
    messagingSenderId: '886615549436',
    projectId: 'flutter-test-a0946',
    authDomain: 'flutter-test-a0946.firebaseapp.com',
    storageBucket: 'flutter-test-a0946.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRjRVb_Hhmm7r9FZKGMMK6GJv3abUF97E',
    appId: '1:886615549436:android:65ffdc44827406f5693e79',
    messagingSenderId: '886615549436',
    projectId: 'flutter-test-a0946',
    storageBucket: 'flutter-test-a0946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYfWuu4KORs1Juzoz7LaPXS71V79qOpmY',
    appId: '1:886615549436:ios:354aa71374ce24c2693e79',
    messagingSenderId: '886615549436',
    projectId: 'flutter-test-a0946',
    storageBucket: 'flutter-test-a0946.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYfWuu4KORs1Juzoz7LaPXS71V79qOpmY',
    appId: '1:886615549436:ios:354aa71374ce24c2693e79',
    messagingSenderId: '886615549436',
    projectId: 'flutter-test-a0946',
    storageBucket: 'flutter-test-a0946.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
